//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public class ADLX_RGB : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ADLX_RGB(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ADLX_RGB obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ADLX_RGB() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_ADLX_RGB(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double gamutR {
    set {
      ADLXPINVOKE.ADLX_RGB_gamutR_set(swigCPtr, value);
    } 
    get {
      double ret = ADLXPINVOKE.ADLX_RGB_gamutR_get(swigCPtr);
      return ret;
    } 
  }

  public double gamutG {
    set {
      ADLXPINVOKE.ADLX_RGB_gamutG_set(swigCPtr, value);
    } 
    get {
      double ret = ADLXPINVOKE.ADLX_RGB_gamutG_get(swigCPtr);
      return ret;
    } 
  }

  public double gamutB {
    set {
      ADLXPINVOKE.ADLX_RGB_gamutB_set(swigCPtr, value);
    } 
    get {
      double ret = ADLXPINVOKE.ADLX_RGB_gamutB_get(swigCPtr);
      return ret;
    } 
  }

  public ADLX_RGB() : this(ADLXPINVOKE.new_ADLX_RGB(), true) {
  }

}

}
