//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_GAMUT_SPACE {
  GAMUT_SPACE_CCIR_709 = 0,
  GAMUT_SPACE_CCIR_601,
  GAMUT_SPACE_ADOBE_RGB,
  GAMUT_SPACE_CIE_RGB,
  GAMUT_SPACE_CCIR_2020,
  GAMUT_SPACE_CUSTOM
}

}
