//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_ORIENTATION {
  ORIENTATION_LANDSCAPE = 0,
  ORIENTATION_PORTRAIT = 90,
  ORIENTATION_LANDSCAPE_FLIPPED = 180,
  ORIENTATION_PORTRAIT_FLIPPED = 270
}

}
