//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_DISPLAY_TYPE {
  DISPLAY_TYPE_UNKOWN = 0,
  DISPLAY_TYPE_MONITOR,
  DISPLAY_TYPE_TELEVISION,
  DISPLAY_TYPE_LCD_PANEL,
  DISPLAY_TYPE_DIGITAL_FLAT_PANEL,
  DISPLAY_TYPE_COMPONENT_VIDEO,
  DISPLAY_TYPE_PROJECTOR
}

}
