//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_PIXEL_FORMAT {
  FORMAT_UNKNOWN = 0,
  RGB_444_FULL,
  YCBCR_444,
  YCBCR_422,
  RGB_444_LIMITED,
  YCBCR_420
}

}
