//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public class ADLX_TimingInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ADLX_TimingInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ADLX_TimingInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ADLX_TimingInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_ADLX_TimingInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int timingFlags {
    set {
      ADLXPINVOKE.ADLX_TimingInfo_timingFlags_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_TimingInfo_timingFlags_get(swigCPtr);
      return ret;
    } 
  }

  public int hTotal {
    set {
      ADLXPINVOKE.ADLX_TimingInfo_hTotal_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_TimingInfo_hTotal_get(swigCPtr);
      return ret;
    } 
  }

  public int vTotal {
    set {
      ADLXPINVOKE.ADLX_TimingInfo_vTotal_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_TimingInfo_vTotal_get(swigCPtr);
      return ret;
    } 
  }

  public int hDisplay {
    set {
      ADLXPINVOKE.ADLX_TimingInfo_hDisplay_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_TimingInfo_hDisplay_get(swigCPtr);
      return ret;
    } 
  }

  public int vDisplay {
    set {
      ADLXPINVOKE.ADLX_TimingInfo_vDisplay_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_TimingInfo_vDisplay_get(swigCPtr);
      return ret;
    } 
  }

  public int hFrontPorch {
    set {
      ADLXPINVOKE.ADLX_TimingInfo_hFrontPorch_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_TimingInfo_hFrontPorch_get(swigCPtr);
      return ret;
    } 
  }

  public int vFrontPorch {
    set {
      ADLXPINVOKE.ADLX_TimingInfo_vFrontPorch_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_TimingInfo_vFrontPorch_get(swigCPtr);
      return ret;
    } 
  }

  public int hSyncWidth {
    set {
      ADLXPINVOKE.ADLX_TimingInfo_hSyncWidth_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_TimingInfo_hSyncWidth_get(swigCPtr);
      return ret;
    } 
  }

  public int vSyncWidth {
    set {
      ADLXPINVOKE.ADLX_TimingInfo_vSyncWidth_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_TimingInfo_vSyncWidth_get(swigCPtr);
      return ret;
    } 
  }

  public int hPolarity {
    set {
      ADLXPINVOKE.ADLX_TimingInfo_hPolarity_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_TimingInfo_hPolarity_get(swigCPtr);
      return ret;
    } 
  }

  public int vPolarity {
    set {
      ADLXPINVOKE.ADLX_TimingInfo_vPolarity_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_TimingInfo_vPolarity_get(swigCPtr);
      return ret;
    } 
  }

  public ADLX_TimingInfo() : this(ADLXPINVOKE.new_ADLX_TimingInfo(), true) {
  }

}

}
