//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_WHITE_POINT {
  WHITE_POINT_5000K = 0,
  WHITE_POINT_6500K,
  WHITE_POINT_7500K,
  WHITE_POINT_9300K,
  WHITE_POINT_CUSTOM
}

}
