//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public class ADLX_IntRange : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ADLX_IntRange(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ADLX_IntRange obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ADLX_IntRange() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_ADLX_IntRange(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int minValue {
    set {
      ADLXPINVOKE.ADLX_IntRange_minValue_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_IntRange_minValue_get(swigCPtr);
      return ret;
    } 
  }

  public int maxValue {
    set {
      ADLXPINVOKE.ADLX_IntRange_maxValue_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_IntRange_maxValue_get(swigCPtr);
      return ret;
    } 
  }

  public int step {
    set {
      ADLXPINVOKE.ADLX_IntRange_step_set(swigCPtr, value);
    } 
    get {
      int ret = ADLXPINVOKE.ADLX_IntRange_step_get(swigCPtr);
      return ret;
    } 
  }

  public ADLX_IntRange() : this(ADLXPINVOKE.new_ADLX_IntRange(), true) {
  }

}

}
