//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public class ADLX {
  public static int adlx_atomic_inc(SWIGTYPE_p_long x) {
    int ret = ADLXPINVOKE.adlx_atomic_inc(SWIGTYPE_p_long.getCPtr(x));
    return ret;
  }

  public static int adlx_atomic_dec(SWIGTYPE_p_long x) {
    int ret = ADLXPINVOKE.adlx_atomic_dec(SWIGTYPE_p_long.getCPtr(x));
    return ret;
  }

  public static SWIGTYPE_p_void adlx_load_library(SWIGTYPE_p_wchar_t filename) {
    global::System.IntPtr cPtr = ADLXPINVOKE.adlx_load_library(SWIGTYPE_p_wchar_t.getCPtr(filename));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public static int adlx_free_library(SWIGTYPE_p_void module) {
    int ret = ADLXPINVOKE.adlx_free_library(SWIGTYPE_p_void.getCPtr(module));
    return ret;
  }

  public static SWIGTYPE_p_void adlx_get_proc_address(SWIGTYPE_p_void module, string procName) {
    global::System.IntPtr cPtr = ADLXPINVOKE.adlx_get_proc_address(SWIGTYPE_p_void.getCPtr(module), procName);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public static ADLXHelper g_ADLX {
    set {
      ADLXPINVOKE.g_ADLX_set(ADLXHelper.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ADLXPINVOKE.g_ADLX_get();
      ADLXHelper ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLXHelper(cPtr, false);
      return ret;
    } 
  }

  public static SWIGTYPE_p_int new_intP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_intP();
    SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_int copy_intP(int value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_intP(value);
    SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    return ret;
  }

  public static void delete_intP(SWIGTYPE_p_int obj) {
    ADLXPINVOKE.delete_intP(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static void intP_assign(SWIGTYPE_p_int obj, int value) {
    ADLXPINVOKE.intP_assign(SWIGTYPE_p_int.getCPtr(obj), value);
  }

  public static int intP_value(SWIGTYPE_p_int obj) {
    int ret = ADLXPINVOKE.intP_value(SWIGTYPE_p_int.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_double new_doubleP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_doubleP();
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_double copy_doubleP(double value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_doubleP(value);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public static void delete_doubleP(SWIGTYPE_p_double obj) {
    ADLXPINVOKE.delete_doubleP(SWIGTYPE_p_double.getCPtr(obj));
  }

  public static void doubleP_assign(SWIGTYPE_p_double obj, double value) {
    ADLXPINVOKE.doubleP_assign(SWIGTYPE_p_double.getCPtr(obj), value);
  }

  public static double doubleP_value(SWIGTYPE_p_double obj) {
    double ret = ADLXPINVOKE.doubleP_value(SWIGTYPE_p_double.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_unsigned_int new_uintP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_uintP();
    SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_unsigned_int copy_uintP(uint value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_uintP(value);
    SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
    return ret;
  }

  public static void delete_uintP(SWIGTYPE_p_unsigned_int obj) {
    ADLXPINVOKE.delete_uintP(SWIGTYPE_p_unsigned_int.getCPtr(obj));
  }

  public static void uintP_assign(SWIGTYPE_p_unsigned_int obj, uint value) {
    ADLXPINVOKE.uintP_assign(SWIGTYPE_p_unsigned_int.getCPtr(obj), value);
  }

  public static uint uintP_value(SWIGTYPE_p_unsigned_int obj) {
    uint ret = ADLXPINVOKE.uintP_value(SWIGTYPE_p_unsigned_int.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_TYPE new_displayTypeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_displayTypeP();
    SWIGTYPE_p_ADLX_DISPLAY_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_TYPE(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_TYPE copy_displayTypeP(ADLX_DISPLAY_TYPE value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_displayTypeP((int)value);
    SWIGTYPE_p_ADLX_DISPLAY_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_TYPE(cPtr, false);
    return ret;
  }

  public static void delete_displayTypeP(SWIGTYPE_p_ADLX_DISPLAY_TYPE obj) {
    ADLXPINVOKE.delete_displayTypeP(SWIGTYPE_p_ADLX_DISPLAY_TYPE.getCPtr(obj));
  }

  public static void displayTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_TYPE obj, ADLX_DISPLAY_TYPE value) {
    ADLXPINVOKE.displayTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_TYPE.getCPtr(obj), (int)value);
  }

  public static ADLX_DISPLAY_TYPE displayTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_TYPE obj) {
    ADLX_DISPLAY_TYPE ret = (ADLX_DISPLAY_TYPE)ADLXPINVOKE.displayTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_TYPE.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE new_disConnectTypeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_disConnectTypeP();
    SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE copy_disConnectTypeP(ADLX_DISPLAY_CONNECTOR_TYPE value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_disConnectTypeP((int)value);
    SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE(cPtr, false);
    return ret;
  }

  public static void delete_disConnectTypeP(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE obj) {
    ADLXPINVOKE.delete_disConnectTypeP(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE.getCPtr(obj));
  }

  public static void disConnectTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE obj, ADLX_DISPLAY_CONNECTOR_TYPE value) {
    ADLXPINVOKE.disConnectTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE.getCPtr(obj), (int)value);
  }

  public static ADLX_DISPLAY_CONNECTOR_TYPE disConnectTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE obj) {
    ADLX_DISPLAY_CONNECTOR_TYPE ret = (ADLX_DISPLAY_CONNECTOR_TYPE)ADLXPINVOKE.disConnectTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_CONNECTOR_TYPE.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE new_disScanTypeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_disScanTypeP();
    SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE copy_disScanTypeP(ADLX_DISPLAY_SCAN_TYPE value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_disScanTypeP((int)value);
    SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE(cPtr, false);
    return ret;
  }

  public static void delete_disScanTypeP(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE obj) {
    ADLXPINVOKE.delete_disScanTypeP(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE.getCPtr(obj));
  }

  public static void disScanTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE obj, ADLX_DISPLAY_SCAN_TYPE value) {
    ADLXPINVOKE.disScanTypeP_assign(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE.getCPtr(obj), (int)value);
  }

  public static ADLX_DISPLAY_SCAN_TYPE disScanTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE obj) {
    ADLX_DISPLAY_SCAN_TYPE ret = (ADLX_DISPLAY_SCAN_TYPE)ADLXPINVOKE.disScanTypeP_value(SWIGTYPE_p_ADLX_DISPLAY_SCAN_TYPE.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_size_t new_adlx_sizeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_adlx_sizeP();
    SWIGTYPE_p_size_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_size_t(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_size_t copy_adlx_sizeP(uint value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_adlx_sizeP(value);
    SWIGTYPE_p_size_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_size_t(cPtr, false);
    return ret;
  }

  public static void delete_adlx_sizeP(SWIGTYPE_p_size_t obj) {
    ADLXPINVOKE.delete_adlx_sizeP(SWIGTYPE_p_size_t.getCPtr(obj));
  }

  public static void adlx_sizeP_assign(SWIGTYPE_p_size_t obj, uint value) {
    ADLXPINVOKE.adlx_sizeP_assign(SWIGTYPE_p_size_t.getCPtr(obj), value);
  }

  public static uint adlx_sizeP_value(SWIGTYPE_p_size_t obj) {
    uint ret = ADLXPINVOKE.adlx_sizeP_value(SWIGTYPE_p_size_t.getCPtr(obj));
    return ret;
  }

  public static ADLX_RGB new_rgbTypeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_rgbTypeP();
    ADLX_RGB ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLX_RGB(cPtr, false);
    return ret;
  }

  public static ADLX_RGB copy_rgbTypeP(ADLX_RGB value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_rgbTypeP(ADLX_RGB.getCPtr(value));
    ADLX_RGB ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLX_RGB(cPtr, false);
    if (ADLXPINVOKE.SWIGPendingException.Pending) throw ADLXPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void delete_rgbTypeP(ADLX_RGB obj) {
    ADLXPINVOKE.delete_rgbTypeP(ADLX_RGB.getCPtr(obj));
  }

  public static void rgbTypeP_assign(ADLX_RGB obj, ADLX_RGB value) {
    ADLXPINVOKE.rgbTypeP_assign(ADLX_RGB.getCPtr(obj), ADLX_RGB.getCPtr(value));
    if (ADLXPINVOKE.SWIGPendingException.Pending) throw ADLXPINVOKE.SWIGPendingException.Retrieve();
  }

  public static ADLX_RGB rgbTypeP_value(ADLX_RGB obj) {
    ADLX_RGB ret = new ADLX_RGB(ADLXPINVOKE.rgbTypeP_value(ADLX_RGB.getCPtr(obj)), true);
    return ret;
  }

  public static ADLX_Point new_pointTypeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_pointTypeP();
    ADLX_Point ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLX_Point(cPtr, false);
    return ret;
  }

  public static ADLX_Point copy_pointTypeP(ADLX_Point value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_pointTypeP(ADLX_Point.getCPtr(value));
    ADLX_Point ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLX_Point(cPtr, false);
    if (ADLXPINVOKE.SWIGPendingException.Pending) throw ADLXPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void delete_pointTypeP(ADLX_Point obj) {
    ADLXPINVOKE.delete_pointTypeP(ADLX_Point.getCPtr(obj));
  }

  public static void pointTypeP_assign(ADLX_Point obj, ADLX_Point value) {
    ADLXPINVOKE.pointTypeP_assign(ADLX_Point.getCPtr(obj), ADLX_Point.getCPtr(value));
    if (ADLXPINVOKE.SWIGPendingException.Pending) throw ADLXPINVOKE.SWIGPendingException.Retrieve();
  }

  public static ADLX_Point pointTypeP_value(ADLX_Point obj) {
    ADLX_Point ret = new ADLX_Point(ADLXPINVOKE.pointTypeP_value(ADLX_Point.getCPtr(obj)), true);
    return ret;
  }

  public static ADLX_IntRange new_intRangeTypeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_intRangeTypeP();
    ADLX_IntRange ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLX_IntRange(cPtr, false);
    return ret;
  }

  public static ADLX_IntRange copy_intRangeTypeP(ADLX_IntRange value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_intRangeTypeP(ADLX_IntRange.getCPtr(value));
    ADLX_IntRange ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLX_IntRange(cPtr, false);
    if (ADLXPINVOKE.SWIGPendingException.Pending) throw ADLXPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void delete_intRangeTypeP(ADLX_IntRange obj) {
    ADLXPINVOKE.delete_intRangeTypeP(ADLX_IntRange.getCPtr(obj));
  }

  public static void intRangeTypeP_assign(ADLX_IntRange obj, ADLX_IntRange value) {
    ADLXPINVOKE.intRangeTypeP_assign(ADLX_IntRange.getCPtr(obj), ADLX_IntRange.getCPtr(value));
    if (ADLXPINVOKE.SWIGPendingException.Pending) throw ADLXPINVOKE.SWIGPendingException.Retrieve();
  }

  public static ADLX_IntRange intRangeTypeP_value(ADLX_IntRange obj) {
    ADLX_IntRange ret = new ADLX_IntRange(ADLXPINVOKE.intRangeTypeP_value(ADLX_IntRange.getCPtr(obj)), true);
    return ret;
  }

  public static ADLX_UINT16_RGB new_uint16RgbTypeP() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_uint16RgbTypeP();
    ADLX_UINT16_RGB ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLX_UINT16_RGB(cPtr, false);
    return ret;
  }

  public static ADLX_UINT16_RGB copy_uint16RgbTypeP(ADLX_UINT16_RGB value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_uint16RgbTypeP(ADLX_UINT16_RGB.getCPtr(value));
    ADLX_UINT16_RGB ret = (cPtr == global::System.IntPtr.Zero) ? null : new ADLX_UINT16_RGB(cPtr, false);
    if (ADLXPINVOKE.SWIGPendingException.Pending) throw ADLXPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void delete_uint16RgbTypeP(ADLX_UINT16_RGB obj) {
    ADLXPINVOKE.delete_uint16RgbTypeP(ADLX_UINT16_RGB.getCPtr(obj));
  }

  public static void uint16RgbTypeP_assign(ADLX_UINT16_RGB obj, ADLX_UINT16_RGB value) {
    ADLXPINVOKE.uint16RgbTypeP_assign(ADLX_UINT16_RGB.getCPtr(obj), ADLX_UINT16_RGB.getCPtr(value));
    if (ADLXPINVOKE.SWIGPendingException.Pending) throw ADLXPINVOKE.SWIGPendingException.Retrieve();
  }

  public static ADLX_UINT16_RGB uint16RgbTypeP_value(ADLX_UINT16_RGB obj) {
    ADLX_UINT16_RGB ret = new ADLX_UINT16_RGB(ADLXPINVOKE.uint16RgbTypeP_value(ADLX_UINT16_RGB.getCPtr(obj)), true);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXDisplayServices new_displayServicesP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_displayServicesP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXDisplayServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXDisplayServices(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXDisplayServices copy_displayServicesP_Ptr(IADLXDisplayServices value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_displayServicesP_Ptr(IADLXDisplayServices.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXDisplayServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXDisplayServices(cPtr, false);
    return ret;
  }

  public static void delete_displayServicesP_Ptr(SWIGTYPE_p_p_adlx__IADLXDisplayServices obj) {
    ADLXPINVOKE.delete_displayServicesP_Ptr(SWIGTYPE_p_p_adlx__IADLXDisplayServices.getCPtr(obj));
  }

  public static void displayServicesP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXDisplayServices obj, IADLXDisplayServices value) {
    ADLXPINVOKE.displayServicesP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXDisplayServices.getCPtr(obj), IADLXDisplayServices.getCPtr(value));
  }

  public static IADLXDisplayServices displayServicesP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXDisplayServices obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.displayServicesP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXDisplayServices.getCPtr(obj));
    IADLXDisplayServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXDisplayServices(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXDisplayList new_displayListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_displayListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXDisplayList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXDisplayList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXDisplayList copy_displayListP_Ptr(IADLXDisplayList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_displayListP_Ptr(IADLXDisplayList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXDisplayList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXDisplayList(cPtr, false);
    return ret;
  }

  public static void delete_displayListP_Ptr(SWIGTYPE_p_p_adlx__IADLXDisplayList obj) {
    ADLXPINVOKE.delete_displayListP_Ptr(SWIGTYPE_p_p_adlx__IADLXDisplayList.getCPtr(obj));
  }

  public static void displayListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXDisplayList obj, IADLXDisplayList value) {
    ADLXPINVOKE.displayListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXDisplayList.getCPtr(obj), IADLXDisplayList.getCPtr(value));
  }

  public static IADLXDisplayList displayListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXDisplayList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.displayListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXDisplayList.getCPtr(obj));
    IADLXDisplayList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXDisplayList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXDisplay new_displayP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_displayP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXDisplay ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXDisplay(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXDisplay copy_displayP_Ptr(IADLXDisplay value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_displayP_Ptr(IADLXDisplay.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXDisplay ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXDisplay(cPtr, false);
    return ret;
  }

  public static void delete_displayP_Ptr(SWIGTYPE_p_p_adlx__IADLXDisplay obj) {
    ADLXPINVOKE.delete_displayP_Ptr(SWIGTYPE_p_p_adlx__IADLXDisplay.getCPtr(obj));
  }

  public static void displayP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXDisplay obj, IADLXDisplay value) {
    ADLXPINVOKE.displayP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXDisplay.getCPtr(obj), IADLXDisplay.getCPtr(value));
  }

  public static IADLXDisplay displayP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXDisplay obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.displayP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXDisplay.getCPtr(obj));
    IADLXDisplay ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXDisplay(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling new_displayChangeHandlingP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_displayChangeHandlingP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling copy_displayChangeHandlingP_Ptr(IADLXDisplayChangedHandling value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_displayChangeHandlingP_Ptr(IADLXDisplayChangedHandling.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling(cPtr, false);
    return ret;
  }

  public static void delete_displayChangeHandlingP_Ptr(SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling obj) {
    ADLXPINVOKE.delete_displayChangeHandlingP_Ptr(SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling.getCPtr(obj));
  }

  public static void displayChangeHandlingP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling obj, IADLXDisplayChangedHandling value) {
    ADLXPINVOKE.displayChangeHandlingP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling.getCPtr(obj), IADLXDisplayChangedHandling.getCPtr(value));
  }

  public static IADLXDisplayChangedHandling displayChangeHandlingP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.displayChangeHandlingP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXDisplayChangedHandling.getCPtr(obj));
    IADLXDisplayChangedHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXDisplayChangedHandling(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_char new_charP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_charP_Ptr();
    SWIGTYPE_p_p_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_char copy_charP_Ptr(string value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_charP_Ptr(value);
    SWIGTYPE_p_p_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
    return ret;
  }

  public static void delete_charP_Ptr(SWIGTYPE_p_p_char obj) {
    ADLXPINVOKE.delete_charP_Ptr(SWIGTYPE_p_p_char.getCPtr(obj));
  }

  public static void charP_Ptr_assign(SWIGTYPE_p_p_char obj, string value) {
    ADLXPINVOKE.charP_Ptr_assign(SWIGTYPE_p_p_char.getCPtr(obj), value);
  }

  public static string charP_Ptr_value(SWIGTYPE_p_p_char obj) {
    string ret = ADLXPINVOKE.charP_Ptr_value(SWIGTYPE_p_p_char.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuningState new_manualFanTuningStateP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualFanTuningStateP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualFanTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuningState(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuningState copy_manualFanTuningStateP_Ptr(IADLXManualFanTuningState value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualFanTuningStateP_Ptr(IADLXManualFanTuningState.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualFanTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuningState(cPtr, false);
    return ret;
  }

  public static void delete_manualFanTuningStateP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState obj) {
    ADLXPINVOKE.delete_manualFanTuningStateP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState.getCPtr(obj));
  }

  public static void manualFanTuningStateP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState obj, IADLXManualFanTuningState value) {
    ADLXPINVOKE.manualFanTuningStateP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState.getCPtr(obj), IADLXManualFanTuningState.getCPtr(value));
  }

  public static IADLXManualFanTuningState manualFanTuningStateP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualFanTuningStateP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuningState.getCPtr(obj));
    IADLXManualFanTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualFanTuningState(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList new_manualFanTuningStateListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualFanTuningStateListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList copy_manualFanTuningStateListP_Ptr(IADLXManualFanTuningStateList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualFanTuningStateListP_Ptr(IADLXManualFanTuningStateList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList(cPtr, false);
    return ret;
  }

  public static void delete_manualFanTuningStateListP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList obj) {
    ADLXPINVOKE.delete_manualFanTuningStateListP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList.getCPtr(obj));
  }

  public static void manualFanTuningStateListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList obj, IADLXManualFanTuningStateList value) {
    ADLXPINVOKE.manualFanTuningStateListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList.getCPtr(obj), IADLXManualFanTuningStateList.getCPtr(value));
  }

  public static IADLXManualFanTuningStateList manualFanTuningStateListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualFanTuningStateListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuningStateList.getCPtr(obj));
    IADLXManualFanTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualFanTuningStateList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuning new_manualFanTuningP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualFanTuningP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualFanTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuning(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualFanTuning copy_manualFanTuningP_Ptr(IADLXManualFanTuning value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualFanTuningP_Ptr(IADLXManualFanTuning.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualFanTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualFanTuning(cPtr, false);
    return ret;
  }

  public static void delete_manualFanTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuning obj) {
    ADLXPINVOKE.delete_manualFanTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualFanTuning.getCPtr(obj));
  }

  public static void manualFanTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuning obj, IADLXManualFanTuning value) {
    ADLXPINVOKE.manualFanTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualFanTuning.getCPtr(obj), IADLXManualFanTuning.getCPtr(value));
  }

  public static IADLXManualFanTuning manualFanTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuning obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualFanTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualFanTuning.getCPtr(obj));
    IADLXManualFanTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualFanTuning(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 new_manualGraphicsTuning1P_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualGraphicsTuning1P_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 copy_manualGraphicsTuning1P_Ptr(IADLXManualGraphicsTuning1 value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualGraphicsTuning1P_Ptr(IADLXManualGraphicsTuning1.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1(cPtr, false);
    return ret;
  }

  public static void delete_manualGraphicsTuning1P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 obj) {
    ADLXPINVOKE.delete_manualGraphicsTuning1P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1.getCPtr(obj));
  }

  public static void manualGraphicsTuning1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 obj, IADLXManualGraphicsTuning1 value) {
    ADLXPINVOKE.manualGraphicsTuning1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1.getCPtr(obj), IADLXManualGraphicsTuning1.getCPtr(value));
  }

  public static IADLXManualGraphicsTuning1 manualGraphicsTuning1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1 obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualGraphicsTuning1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning1.getCPtr(obj));
    IADLXManualGraphicsTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualGraphicsTuning1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 new_manualGraphicsTuning2P_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualGraphicsTuning2P_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 copy_manualGraphicsTuning2P_Ptr(IADLXManualGraphicsTuning2 value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualGraphicsTuning2P_Ptr(IADLXManualGraphicsTuning2.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2(cPtr, false);
    return ret;
  }

  public static void delete_manualGraphicsTuning2P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 obj) {
    ADLXPINVOKE.delete_manualGraphicsTuning2P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2.getCPtr(obj));
  }

  public static void manualGraphicsTuning2P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 obj, IADLXManualGraphicsTuning2 value) {
    ADLXPINVOKE.manualGraphicsTuning2P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2.getCPtr(obj), IADLXManualGraphicsTuning2.getCPtr(value));
  }

  public static IADLXManualGraphicsTuning2 manualGraphicsTuning2P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2 obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualGraphicsTuning2P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualGraphicsTuning2.getCPtr(obj));
    IADLXManualGraphicsTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualGraphicsTuning2(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualPowerTuning new_manualPowerTuningP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualPowerTuningP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualPowerTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualPowerTuning(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualPowerTuning copy_manualPowerTuningP_Ptr(IADLXManualPowerTuning value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualPowerTuningP_Ptr(IADLXManualPowerTuning.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualPowerTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualPowerTuning(cPtr, false);
    return ret;
  }

  public static void delete_manualPowerTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning obj) {
    ADLXPINVOKE.delete_manualPowerTuningP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning.getCPtr(obj));
  }

  public static void manualPowerTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning obj, IADLXManualPowerTuning value) {
    ADLXPINVOKE.manualPowerTuningP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning.getCPtr(obj), IADLXManualPowerTuning.getCPtr(value));
  }

  public static IADLXManualPowerTuning manualPowerTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualPowerTuningP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualPowerTuning.getCPtr(obj));
    IADLXManualPowerTuning ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualPowerTuning(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList new_memoryTimingDescriptionListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_memoryTimingDescriptionListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList copy_memoryTimingDescriptionListP_Ptr(IADLXMemoryTimingDescriptionList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_memoryTimingDescriptionListP_Ptr(IADLXMemoryTimingDescriptionList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList(cPtr, false);
    return ret;
  }

  public static void delete_memoryTimingDescriptionListP_Ptr(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList obj) {
    ADLXPINVOKE.delete_memoryTimingDescriptionListP_Ptr(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList.getCPtr(obj));
  }

  public static void memoryTimingDescriptionListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList obj, IADLXMemoryTimingDescriptionList value) {
    ADLXPINVOKE.memoryTimingDescriptionListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList.getCPtr(obj), IADLXMemoryTimingDescriptionList.getCPtr(value));
  }

  public static IADLXMemoryTimingDescriptionList memoryTimingDescriptionListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.memoryTimingDescriptionListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList.getCPtr(obj));
    IADLXMemoryTimingDescriptionList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXMemoryTimingDescriptionList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 new_manualVramTuning1P_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualVramTuning1P_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 copy_manualVramTuning1P_Ptr(IADLXManualVRAMTuning1 value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualVramTuning1P_Ptr(IADLXManualVRAMTuning1.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1(cPtr, false);
    return ret;
  }

  public static void delete_manualVramTuning1P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 obj) {
    ADLXPINVOKE.delete_manualVramTuning1P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1.getCPtr(obj));
  }

  public static void manualVramTuning1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 obj, IADLXManualVRAMTuning1 value) {
    ADLXPINVOKE.manualVramTuning1P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1.getCPtr(obj), IADLXManualVRAMTuning1.getCPtr(value));
  }

  public static IADLXManualVRAMTuning1 manualVramTuning1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1 obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualVramTuning1P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning1.getCPtr(obj));
    IADLXManualVRAMTuning1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualVRAMTuning1(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 new_manualVramTuning2P_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualVramTuning2P_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 copy_manualVramTuning2P_Ptr(IADLXManualVRAMTuning2 value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualVramTuning2P_Ptr(IADLXManualVRAMTuning2.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2(cPtr, false);
    return ret;
  }

  public static void delete_manualVramTuning2P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 obj) {
    ADLXPINVOKE.delete_manualVramTuning2P_Ptr(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2.getCPtr(obj));
  }

  public static void manualVramTuning2P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 obj, IADLXManualVRAMTuning2 value) {
    ADLXPINVOKE.manualVramTuning2P_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2.getCPtr(obj), IADLXManualVRAMTuning2.getCPtr(value));
  }

  public static IADLXManualVRAMTuning2 manualVramTuning2P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2 obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualVramTuning2P_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualVRAMTuning2.getCPtr(obj));
    IADLXManualVRAMTuning2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualVRAMTuning2(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualTuningState new_manualTuningStateP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualTuningStateP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualTuningState(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualTuningState copy_manualTuningStateP_Ptr(IADLXManualTuningState value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualTuningStateP_Ptr(IADLXManualTuningState.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualTuningState(cPtr, false);
    return ret;
  }

  public static void delete_manualTuningStateP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualTuningState obj) {
    ADLXPINVOKE.delete_manualTuningStateP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualTuningState.getCPtr(obj));
  }

  public static void manualTuningStateP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualTuningState obj, IADLXManualTuningState value) {
    ADLXPINVOKE.manualTuningStateP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualTuningState.getCPtr(obj), IADLXManualTuningState.getCPtr(value));
  }

  public static IADLXManualTuningState manualTuningStateP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualTuningState obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualTuningStateP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualTuningState.getCPtr(obj));
    IADLXManualTuningState ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualTuningState(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualTuningStateList new_manualTuningStateListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_manualTuningStateListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXManualTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualTuningStateList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXManualTuningStateList copy_manualTuningStateListP_Ptr(IADLXManualTuningStateList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_manualTuningStateListP_Ptr(IADLXManualTuningStateList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXManualTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXManualTuningStateList(cPtr, false);
    return ret;
  }

  public static void delete_manualTuningStateListP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList obj) {
    ADLXPINVOKE.delete_manualTuningStateListP_Ptr(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList.getCPtr(obj));
  }

  public static void manualTuningStateListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList obj, IADLXManualTuningStateList value) {
    ADLXPINVOKE.manualTuningStateListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList.getCPtr(obj), IADLXManualTuningStateList.getCPtr(value));
  }

  public static IADLXManualTuningStateList manualTuningStateListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.manualTuningStateListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList.getCPtr(obj));
    IADLXManualTuningStateList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXManualTuningStateList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription new_memoryTimingDescriptionP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_memoryTimingDescriptionP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription copy_memoryTimingDescriptionP_Ptr(IADLXMemoryTimingDescription value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_memoryTimingDescriptionP_Ptr(IADLXMemoryTimingDescription.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription(cPtr, false);
    return ret;
  }

  public static void delete_memoryTimingDescriptionP_Ptr(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription obj) {
    ADLXPINVOKE.delete_memoryTimingDescriptionP_Ptr(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription.getCPtr(obj));
  }

  public static void memoryTimingDescriptionP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription obj, IADLXMemoryTimingDescription value) {
    ADLXPINVOKE.memoryTimingDescriptionP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription.getCPtr(obj), IADLXMemoryTimingDescription.getCPtr(value));
  }

  public static IADLXMemoryTimingDescription memoryTimingDescriptionP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.memoryTimingDescriptionP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescription.getCPtr(obj));
    IADLXMemoryTimingDescription ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXMemoryTimingDescription(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent new_gpuTuningChangedEventP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuTuningChangedEventP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent copy_gpuTuningChangedEventP_Ptr(IADLXGPUTuningChangedEvent value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuTuningChangedEventP_Ptr(IADLXGPUTuningChangedEvent.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent(cPtr, false);
    return ret;
  }

  public static void delete_gpuTuningChangedEventP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent obj) {
    ADLXPINVOKE.delete_gpuTuningChangedEventP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent.getCPtr(obj));
  }

  public static void gpuTuningChangedEventP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent obj, IADLXGPUTuningChangedEvent value) {
    ADLXPINVOKE.gpuTuningChangedEventP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent.getCPtr(obj), IADLXGPUTuningChangedEvent.getCPtr(value));
  }

  public static IADLXGPUTuningChangedEvent gpuTuningChangedEventP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuTuningChangedEventP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedEvent.getCPtr(obj));
    IADLXGPUTuningChangedEvent ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUTuningChangedEvent(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener new_gpuTuningChangedListenerP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuTuningChangedListenerP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener copy_gpuTuningChangedListenerP_Ptr(IADLXGPUTuningChangedListener value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuTuningChangedListenerP_Ptr(IADLXGPUTuningChangedListener.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener(cPtr, false);
    return ret;
  }

  public static void delete_gpuTuningChangedListenerP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener obj) {
    ADLXPINVOKE.delete_gpuTuningChangedListenerP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener.getCPtr(obj));
  }

  public static void gpuTuningChangedListenerP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener obj, IADLXGPUTuningChangedListener value) {
    ADLXPINVOKE.gpuTuningChangedListenerP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener.getCPtr(obj), IADLXGPUTuningChangedListener.getCPtr(value));
  }

  public static IADLXGPUTuningChangedListener gpuTuningChangedListenerP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuTuningChangedListenerP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedListener.getCPtr(obj));
    IADLXGPUTuningChangedListener ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUTuningChangedListener(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling new_gpuTuningChangedHandlingP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuTuningChangedHandlingP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling copy_gpuTuningChangedHandlingP_Ptr(IADLXGPUTuningChangedHandling value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuTuningChangedHandlingP_Ptr(IADLXGPUTuningChangedHandling.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling(cPtr, false);
    return ret;
  }

  public static void delete_gpuTuningChangedHandlingP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling obj) {
    ADLXPINVOKE.delete_gpuTuningChangedHandlingP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling.getCPtr(obj));
  }

  public static void gpuTuningChangedHandlingP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling obj, IADLXGPUTuningChangedHandling value) {
    ADLXPINVOKE.gpuTuningChangedHandlingP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling.getCPtr(obj), IADLXGPUTuningChangedHandling.getCPtr(value));
  }

  public static IADLXGPUTuningChangedHandling gpuTuningChangedHandlingP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuTuningChangedHandlingP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUTuningChangedHandling.getCPtr(obj));
    IADLXGPUTuningChangedHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUTuningChangedHandling(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUTuningServices new_gpuTuningServicesP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuTuningServicesP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUTuningServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUTuningServices(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUTuningServices copy_gpuTuningServicesP_Ptr(IADLXGPUTuningServices value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuTuningServicesP_Ptr(IADLXGPUTuningServices.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUTuningServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUTuningServices(cPtr, false);
    return ret;
  }

  public static void delete_gpuTuningServicesP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices obj) {
    ADLXPINVOKE.delete_gpuTuningServicesP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices.getCPtr(obj));
  }

  public static void gpuTuningServicesP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices obj, IADLXGPUTuningServices value) {
    ADLXPINVOKE.gpuTuningServicesP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices.getCPtr(obj), IADLXGPUTuningServices.getCPtr(value));
  }

  public static IADLXGPUTuningServices gpuTuningServicesP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuTuningServicesP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUTuningServices.getCPtr(obj));
    IADLXGPUTuningServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUTuningServices(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport new_gpuMetricsSupportP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuMetricsSupportP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport copy_gpuMetricsSupportP_Ptr(IADLXGPUMetricsSupport value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuMetricsSupportP_Ptr(IADLXGPUMetricsSupport.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport(cPtr, false);
    return ret;
  }

  public static void delete_gpuMetricsSupportP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport obj) {
    ADLXPINVOKE.delete_gpuMetricsSupportP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport.getCPtr(obj));
  }

  public static void gpuMetricsSupportP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport obj, IADLXGPUMetricsSupport value) {
    ADLXPINVOKE.gpuMetricsSupportP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport.getCPtr(obj), IADLXGPUMetricsSupport.getCPtr(value));
  }

  public static IADLXGPUMetricsSupport gpuMetricsSupportP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuMetricsSupportP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport.getCPtr(obj));
    IADLXGPUMetricsSupport ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUMetricsSupport(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport new_systemMetricsSupportP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_systemMetricsSupportP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport copy_systemMetricsSupportP_Ptr(IADLXSystemMetricsSupport value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_systemMetricsSupportP_Ptr(IADLXSystemMetricsSupport.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport(cPtr, false);
    return ret;
  }

  public static void delete_systemMetricsSupportP_Ptr(SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport obj) {
    ADLXPINVOKE.delete_systemMetricsSupportP_Ptr(SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport.getCPtr(obj));
  }

  public static void systemMetricsSupportP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport obj, IADLXSystemMetricsSupport value) {
    ADLXPINVOKE.systemMetricsSupportP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport.getCPtr(obj), IADLXSystemMetricsSupport.getCPtr(value));
  }

  public static IADLXSystemMetricsSupport systemMetricsSupportP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.systemMetricsSupportP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport.getCPtr(obj));
    IADLXSystemMetricsSupport ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXSystemMetricsSupport(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetrics new_gpuMetricsP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuMetricsP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetrics(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetrics copy_gpuMetricsP_Ptr(IADLXGPUMetrics value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuMetricsP_Ptr(IADLXGPUMetrics.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetrics(cPtr, false);
    return ret;
  }

  public static void delete_gpuMetricsP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetrics obj) {
    ADLXPINVOKE.delete_gpuMetricsP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetrics.getCPtr(obj));
  }

  public static void gpuMetricsP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetrics obj, IADLXGPUMetrics value) {
    ADLXPINVOKE.gpuMetricsP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetrics.getCPtr(obj), IADLXGPUMetrics.getCPtr(value));
  }

  public static IADLXGPUMetrics gpuMetricsP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetrics obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuMetricsP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetrics.getCPtr(obj));
    IADLXGPUMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUMetrics(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetricsList new_gpuMetricsListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuMetricsListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUMetricsList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetricsList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUMetricsList copy_gpuMetricsListP_Ptr(IADLXGPUMetricsList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuMetricsListP_Ptr(IADLXGPUMetricsList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUMetricsList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUMetricsList(cPtr, false);
    return ret;
  }

  public static void delete_gpuMetricsListP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetricsList obj) {
    ADLXPINVOKE.delete_gpuMetricsListP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUMetricsList.getCPtr(obj));
  }

  public static void gpuMetricsListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetricsList obj, IADLXGPUMetricsList value) {
    ADLXPINVOKE.gpuMetricsListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUMetricsList.getCPtr(obj), IADLXGPUMetricsList.getCPtr(value));
  }

  public static IADLXGPUMetricsList gpuMetricsListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetricsList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuMetricsListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUMetricsList.getCPtr(obj));
    IADLXGPUMetricsList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUMetricsList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXSystemMetrics new_systemMetricsP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_systemMetricsP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXSystemMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXSystemMetrics(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXSystemMetrics copy_systemMetricsP_Ptr(IADLXSystemMetrics value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_systemMetricsP_Ptr(IADLXSystemMetrics.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXSystemMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXSystemMetrics(cPtr, false);
    return ret;
  }

  public static void delete_systemMetricsP_Ptr(SWIGTYPE_p_p_adlx__IADLXSystemMetrics obj) {
    ADLXPINVOKE.delete_systemMetricsP_Ptr(SWIGTYPE_p_p_adlx__IADLXSystemMetrics.getCPtr(obj));
  }

  public static void systemMetricsP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXSystemMetrics obj, IADLXSystemMetrics value) {
    ADLXPINVOKE.systemMetricsP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXSystemMetrics.getCPtr(obj), IADLXSystemMetrics.getCPtr(value));
  }

  public static IADLXSystemMetrics systemMetricsP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXSystemMetrics obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.systemMetricsP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXSystemMetrics.getCPtr(obj));
    IADLXSystemMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXSystemMetrics(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXSystemMetricsList new_systemMetricsListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_systemMetricsListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXSystemMetricsList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXSystemMetricsList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXSystemMetricsList copy_systemMetricsListP_Ptr(IADLXSystemMetricsList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_systemMetricsListP_Ptr(IADLXSystemMetricsList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXSystemMetricsList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXSystemMetricsList(cPtr, false);
    return ret;
  }

  public static void delete_systemMetricsListP_Ptr(SWIGTYPE_p_p_adlx__IADLXSystemMetricsList obj) {
    ADLXPINVOKE.delete_systemMetricsListP_Ptr(SWIGTYPE_p_p_adlx__IADLXSystemMetricsList.getCPtr(obj));
  }

  public static void systemMetricsListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXSystemMetricsList obj, IADLXSystemMetricsList value) {
    ADLXPINVOKE.systemMetricsListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXSystemMetricsList.getCPtr(obj), IADLXSystemMetricsList.getCPtr(value));
  }

  public static IADLXSystemMetricsList systemMetricsListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXSystemMetricsList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.systemMetricsListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXSystemMetricsList.getCPtr(obj));
    IADLXSystemMetricsList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXSystemMetricsList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXFPS new_fpsP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_fpsP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXFPS ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXFPS(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXFPS copy_fpsP_Ptr(IADLXFPS value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_fpsP_Ptr(IADLXFPS.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXFPS ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXFPS(cPtr, false);
    return ret;
  }

  public static void delete_fpsP_Ptr(SWIGTYPE_p_p_adlx__IADLXFPS obj) {
    ADLXPINVOKE.delete_fpsP_Ptr(SWIGTYPE_p_p_adlx__IADLXFPS.getCPtr(obj));
  }

  public static void fpsP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXFPS obj, IADLXFPS value) {
    ADLXPINVOKE.fpsP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXFPS.getCPtr(obj), IADLXFPS.getCPtr(value));
  }

  public static IADLXFPS fpsP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXFPS obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.fpsP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXFPS.getCPtr(obj));
    IADLXFPS ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXFPS(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXFPSList new_fpsListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_fpsListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXFPSList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXFPSList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXFPSList copy_fpsListP_Ptr(IADLXFPSList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_fpsListP_Ptr(IADLXFPSList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXFPSList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXFPSList(cPtr, false);
    return ret;
  }

  public static void delete_fpsListP_Ptr(SWIGTYPE_p_p_adlx__IADLXFPSList obj) {
    ADLXPINVOKE.delete_fpsListP_Ptr(SWIGTYPE_p_p_adlx__IADLXFPSList.getCPtr(obj));
  }

  public static void fpsListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXFPSList obj, IADLXFPSList value) {
    ADLXPINVOKE.fpsListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXFPSList.getCPtr(obj), IADLXFPSList.getCPtr(value));
  }

  public static IADLXFPSList fpsListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXFPSList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.fpsListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXFPSList.getCPtr(obj));
    IADLXFPSList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXFPSList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXAllMetrics new_allMetricsP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_allMetricsP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXAllMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXAllMetrics(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXAllMetrics copy_allMetricsP_Ptr(IADLXAllMetrics value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_allMetricsP_Ptr(IADLXAllMetrics.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXAllMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXAllMetrics(cPtr, false);
    return ret;
  }

  public static void delete_allMetricsP_Ptr(SWIGTYPE_p_p_adlx__IADLXAllMetrics obj) {
    ADLXPINVOKE.delete_allMetricsP_Ptr(SWIGTYPE_p_p_adlx__IADLXAllMetrics.getCPtr(obj));
  }

  public static void allMetricsP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXAllMetrics obj, IADLXAllMetrics value) {
    ADLXPINVOKE.allMetricsP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXAllMetrics.getCPtr(obj), IADLXAllMetrics.getCPtr(value));
  }

  public static IADLXAllMetrics allMetricsP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXAllMetrics obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.allMetricsP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXAllMetrics.getCPtr(obj));
    IADLXAllMetrics ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXAllMetrics(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXAllMetricsList new_allMetricsListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_allMetricsListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXAllMetricsList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXAllMetricsList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXAllMetricsList copy_allMetricsListP_Ptr(IADLXAllMetricsList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_allMetricsListP_Ptr(IADLXAllMetricsList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXAllMetricsList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXAllMetricsList(cPtr, false);
    return ret;
  }

  public static void delete_allMetricsListP_Ptr(SWIGTYPE_p_p_adlx__IADLXAllMetricsList obj) {
    ADLXPINVOKE.delete_allMetricsListP_Ptr(SWIGTYPE_p_p_adlx__IADLXAllMetricsList.getCPtr(obj));
  }

  public static void allMetricsListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXAllMetricsList obj, IADLXAllMetricsList value) {
    ADLXPINVOKE.allMetricsListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXAllMetricsList.getCPtr(obj), IADLXAllMetricsList.getCPtr(value));
  }

  public static IADLXAllMetricsList allMetricsListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXAllMetricsList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.allMetricsListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXAllMetricsList.getCPtr(obj));
    IADLXAllMetricsList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXAllMetricsList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices new_performanceMonitoringServicesP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_performanceMonitoringServicesP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices copy_performanceMonitoringServicesP_Ptr(IADLXPerformanceMonitoringServices value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_performanceMonitoringServicesP_Ptr(IADLXPerformanceMonitoringServices.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices(cPtr, false);
    return ret;
  }

  public static void delete_performanceMonitoringServicesP_Ptr(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices obj) {
    ADLXPINVOKE.delete_performanceMonitoringServicesP_Ptr(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices.getCPtr(obj));
  }

  public static void performanceMonitoringServicesP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices obj, IADLXPerformanceMonitoringServices value) {
    ADLXPINVOKE.performanceMonitoringServicesP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices.getCPtr(obj), IADLXPerformanceMonitoringServices.getCPtr(value));
  }

  public static IADLXPerformanceMonitoringServices performanceMonitoringServicesP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.performanceMonitoringServicesP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXPerformanceMonitoringServices.getCPtr(obj));
    IADLXPerformanceMonitoringServices ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXPerformanceMonitoringServices(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPU new_gpuP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPU ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPU(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPU copy_gpuP_Ptr(IADLXGPU value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuP_Ptr(IADLXGPU.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPU ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPU(cPtr, false);
    return ret;
  }

  public static void delete_gpuP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPU obj) {
    ADLXPINVOKE.delete_gpuP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPU.getCPtr(obj));
  }

  public static void gpuP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPU obj, IADLXGPU value) {
    ADLXPINVOKE.gpuP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPU.getCPtr(obj), IADLXGPU.getCPtr(value));
  }

  public static IADLXGPU gpuP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPU obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPU.getCPtr(obj));
    IADLXGPU ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPU(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUList new_gpuListP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpuListP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUList copy_gpuListP_Ptr(IADLXGPUList value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpuListP_Ptr(IADLXGPUList.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUList ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUList(cPtr, false);
    return ret;
  }

  public static void delete_gpuListP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUList obj) {
    ADLXPINVOKE.delete_gpuListP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUList.getCPtr(obj));
  }

  public static void gpuListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUList obj, IADLXGPUList value) {
    ADLXPINVOKE.gpuListP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUList.getCPtr(obj), IADLXGPUList.getCPtr(value));
  }

  public static IADLXGPUList gpuListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUList obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpuListP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUList.getCPtr(obj));
    IADLXGPUList ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUList(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUsEventListener new_gpusEventListenerP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpusEventListenerP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUsEventListener ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUsEventListener(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUsEventListener copy_gpusEventListenerP_Ptr(IADLXGPUsEventListener value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpusEventListenerP_Ptr(IADLXGPUsEventListener.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUsEventListener ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUsEventListener(cPtr, false);
    return ret;
  }

  public static void delete_gpusEventListenerP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUsEventListener obj) {
    ADLXPINVOKE.delete_gpusEventListenerP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUsEventListener.getCPtr(obj));
  }

  public static void gpusEventListenerP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUsEventListener obj, IADLXGPUsEventListener value) {
    ADLXPINVOKE.gpusEventListenerP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUsEventListener.getCPtr(obj), IADLXGPUsEventListener.getCPtr(value));
  }

  public static IADLXGPUsEventListener gpusEventListenerP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUsEventListener obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpusEventListenerP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUsEventListener.getCPtr(obj));
    IADLXGPUsEventListener ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUsEventListener(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling new_gpusChangedHandlingP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_gpusChangedHandlingP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling copy_gpusChangedHandlingP_Ptr(IADLXGPUsChangedHandling value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_gpusChangedHandlingP_Ptr(IADLXGPUsChangedHandling.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling(cPtr, false);
    return ret;
  }

  public static void delete_gpusChangedHandlingP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling obj) {
    ADLXPINVOKE.delete_gpusChangedHandlingP_Ptr(SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling.getCPtr(obj));
  }

  public static void gpusChangedHandlingP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling obj, IADLXGPUsChangedHandling value) {
    ADLXPINVOKE.gpusChangedHandlingP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling.getCPtr(obj), IADLXGPUsChangedHandling.getCPtr(value));
  }

  public static IADLXGPUsChangedHandling gpusChangedHandlingP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.gpusChangedHandlingP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXGPUsChangedHandling.getCPtr(obj));
    IADLXGPUsChangedHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXGPUsChangedHandling(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXSystem new_systemP_Ptr() {
    global::System.IntPtr cPtr = ADLXPINVOKE.new_systemP_Ptr();
    SWIGTYPE_p_p_adlx__IADLXSystem ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXSystem(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_p_adlx__IADLXSystem copy_systemP_Ptr(IADLXSystem value) {
    global::System.IntPtr cPtr = ADLXPINVOKE.copy_systemP_Ptr(IADLXSystem.getCPtr(value));
    SWIGTYPE_p_p_adlx__IADLXSystem ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_adlx__IADLXSystem(cPtr, false);
    return ret;
  }

  public static void delete_systemP_Ptr(SWIGTYPE_p_p_adlx__IADLXSystem obj) {
    ADLXPINVOKE.delete_systemP_Ptr(SWIGTYPE_p_p_adlx__IADLXSystem.getCPtr(obj));
  }

  public static void systemP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXSystem obj, IADLXSystem value) {
    ADLXPINVOKE.systemP_Ptr_assign(SWIGTYPE_p_p_adlx__IADLXSystem.getCPtr(obj), IADLXSystem.getCPtr(value));
  }

  public static IADLXSystem systemP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXSystem obj) {
    global::System.IntPtr cPtr = ADLXPINVOKE.systemP_Ptr_value(SWIGTYPE_p_p_adlx__IADLXSystem.getCPtr(obj));
    IADLXSystem ret = (cPtr == global::System.IntPtr.Zero) ? null : new IADLXSystem(cPtr, false);
    return ret;
  }

  public static readonly int MAX_USER_3DLUT_NUM_POINTS = ADLXPINVOKE.MAX_USER_3DLUT_NUM_POINTS_get();
}

}
