//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_GAMMA_TYPE {
  UNKNOW = 0,
  DEGAMMA_RAMP,
  REGAMMA_RAMP,
  DEGAMMA_COEFFICIENTS,
  REGAMMA_COEFFICIENTS
}

}
