//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_COLOR_DEPTH {
  BPC_UNKNOWN = 0,
  BPC_6,
  BPC_8,
  BPC_10,
  BPC_12,
  BPC_14,
  BPC_16
}

}
