//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_ANTI_ALIASING_METHOD {
  AA_METHOD_MULTISAMPLING = 0,
  AA_METHOD_ADAPTIVE_MULTISAMPLING,
  AA_METHOD_SUPERSAMPLING
}

}
