//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_DISPLAY_TIMING_LIMITATION {
  PIXEL_CLOCK_MAX = 650000,
  PIXEL_CLOCK_MIN = 0,
  REFRESH_RATE_MAX = 200,
  REFRESH_RATE_MIN = 1,
  RESOLUTION_MAX = 9999,
  RESOLUTION_MIN = 1
}

}
