//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE {
  WFVR_ALWAYS_OFF = 0,
  WFVR_OFF_UNLESS_APP_SPECIFIES,
  WFVR_ON_UNLESS_APP_SPECIFIES,
  WFVR_ALWAYS_ON
}

}
