//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_ANTI_ALIASING_MODE {
  AA_MODE_USE_APP_SETTINGS = 0,
  AA_MODE_ENHANCE_APP_SETTINGS,
  AA_MODE_OVERRIDE_APP_SETTINGS
}

}
