//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public class IADLXManualTuningState : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXManualTuningState(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXManualTuningState_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXManualTuningState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXManualTuningState(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXManualTuningState_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT GetFrequency(SWIGTYPE_p_int value) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualTuningState_GetFrequency(swigCPtr, SWIGTYPE_p_int.getCPtr(value));
    return ret;
  }

  public virtual ADLX_RESULT SetFrequency(int value) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualTuningState_SetFrequency(swigCPtr, value);
    return ret;
  }

  public virtual ADLX_RESULT GetVoltage(SWIGTYPE_p_int value) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualTuningState_GetVoltage(swigCPtr, SWIGTYPE_p_int.getCPtr(value));
    return ret;
  }

  public virtual ADLX_RESULT SetVoltage(int value) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualTuningState_SetVoltage(swigCPtr, value);
    return ret;
  }

}

}
