//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public class IADLXPerformanceMonitoringServices : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXPerformanceMonitoringServices(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXPerformanceMonitoringServices_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXPerformanceMonitoringServices obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXPerformanceMonitoringServices(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXPerformanceMonitoringServices_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT GetSamplingIntervalRange(ADLX_IntRange range) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetSamplingIntervalRange(swigCPtr, ADLX_IntRange.getCPtr(range));
    return ret;
  }

  public virtual ADLX_RESULT SetSamplingInterval(int askedIntervalMs) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_SetSamplingInterval(swigCPtr, askedIntervalMs);
    return ret;
  }

  public virtual ADLX_RESULT GetSamplingInterval(SWIGTYPE_p_int intervalMs) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetSamplingInterval(swigCPtr, SWIGTYPE_p_int.getCPtr(intervalMs));
    return ret;
  }

  public virtual ADLX_RESULT GetMaxPerformanceMetricsHistorySizeRange(ADLX_IntRange range) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetMaxPerformanceMetricsHistorySizeRange(swigCPtr, ADLX_IntRange.getCPtr(range));
    return ret;
  }

  public virtual ADLX_RESULT SetMaxPerformanceMetricsHistorySize(int sizeSec) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_SetMaxPerformanceMetricsHistorySize(swigCPtr, sizeSec);
    return ret;
  }

  public virtual ADLX_RESULT GetMaxPerformanceMetricsHistorySize(SWIGTYPE_p_int sizeSec) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetMaxPerformanceMetricsHistorySize(swigCPtr, SWIGTYPE_p_int.getCPtr(sizeSec));
    return ret;
  }

  public virtual ADLX_RESULT ClearPerformanceMetricsHistory() {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_ClearPerformanceMetricsHistory(swigCPtr);
    return ret;
  }

  public virtual ADLX_RESULT GetCurrentPerformanceMetricsHistorySize(SWIGTYPE_p_int sizeSec) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetCurrentPerformanceMetricsHistorySize(swigCPtr, SWIGTYPE_p_int.getCPtr(sizeSec));
    return ret;
  }

  public virtual ADLX_RESULT StartPerformanceMetricsTracking() {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_StartPerformanceMetricsTracking(swigCPtr);
    return ret;
  }

  public virtual ADLX_RESULT StopPerformanceMetricsTracking() {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_StopPerformanceMetricsTracking(swigCPtr);
    return ret;
  }

  public virtual ADLX_RESULT GetAllMetricsHistory(int startMs, int stopMs, SWIGTYPE_p_p_adlx__IADLXAllMetricsList ppMetricsList) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetAllMetricsHistory(swigCPtr, startMs, stopMs, SWIGTYPE_p_p_adlx__IADLXAllMetricsList.getCPtr(ppMetricsList));
    return ret;
  }

  public virtual ADLX_RESULT GetGPUMetricsHistory(IADLXGPU pGPU, int startMs, int stopMs, SWIGTYPE_p_p_adlx__IADLXGPUMetricsList ppMetricsList) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetGPUMetricsHistory(swigCPtr, IADLXGPU.getCPtr(pGPU), startMs, stopMs, SWIGTYPE_p_p_adlx__IADLXGPUMetricsList.getCPtr(ppMetricsList));
    return ret;
  }

  public virtual ADLX_RESULT GetSystemMetricsHistory(int startMs, int stopMs, SWIGTYPE_p_p_adlx__IADLXSystemMetricsList ppMetricsList) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetSystemMetricsHistory(swigCPtr, startMs, stopMs, SWIGTYPE_p_p_adlx__IADLXSystemMetricsList.getCPtr(ppMetricsList));
    return ret;
  }

  public virtual ADLX_RESULT GetFPSHistory(int startMs, int stopMs, SWIGTYPE_p_p_adlx__IADLXFPSList ppMetricsList) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetFPSHistory(swigCPtr, startMs, stopMs, SWIGTYPE_p_p_adlx__IADLXFPSList.getCPtr(ppMetricsList));
    return ret;
  }

  public virtual ADLX_RESULT GetCurrentAllMetrics(SWIGTYPE_p_p_adlx__IADLXAllMetrics ppMetrics) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetCurrentAllMetrics(swigCPtr, SWIGTYPE_p_p_adlx__IADLXAllMetrics.getCPtr(ppMetrics));
    return ret;
  }

  public virtual ADLX_RESULT GetCurrentGPUMetrics(IADLXGPU pGPU, SWIGTYPE_p_p_adlx__IADLXGPUMetrics ppMetrics) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetCurrentGPUMetrics(swigCPtr, IADLXGPU.getCPtr(pGPU), SWIGTYPE_p_p_adlx__IADLXGPUMetrics.getCPtr(ppMetrics));
    return ret;
  }

  public virtual ADLX_RESULT GetCurrentSystemMetrics(SWIGTYPE_p_p_adlx__IADLXSystemMetrics ppMetrics) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetCurrentSystemMetrics(swigCPtr, SWIGTYPE_p_p_adlx__IADLXSystemMetrics.getCPtr(ppMetrics));
    return ret;
  }

  public virtual ADLX_RESULT GetCurrentFPS(SWIGTYPE_p_p_adlx__IADLXFPS ppMetrics) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetCurrentFPS(swigCPtr, SWIGTYPE_p_p_adlx__IADLXFPS.getCPtr(ppMetrics));
    return ret;
  }

  public virtual ADLX_RESULT GetSupportedGPUMetrics(IADLXGPU pGPU, SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport ppMetricsSupported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetSupportedGPUMetrics(swigCPtr, IADLXGPU.getCPtr(pGPU), SWIGTYPE_p_p_adlx__IADLXGPUMetricsSupport.getCPtr(ppMetricsSupported));
    return ret;
  }

  public virtual ADLX_RESULT GetSupportedSystemMetrics(SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport ppMetricsSupported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXPerformanceMonitoringServices_GetSupportedSystemMetrics(swigCPtr, SWIGTYPE_p_p_adlx__IADLXSystemMetricsSupport.getCPtr(ppMetricsSupported));
    return ret;
  }

}

}
