//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public class IADLXGPUMetrics : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXGPUMetrics(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXGPUMetrics_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXGPUMetrics obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXGPUMetrics(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXGPUMetrics_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT TimeStamp(SWIGTYPE_p_long_long ms) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_TimeStamp(swigCPtr, SWIGTYPE_p_long_long.getCPtr(ms));
    return ret;
  }

  public virtual ADLX_RESULT GPUUsage(SWIGTYPE_p_double data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUUsage(swigCPtr, SWIGTYPE_p_double.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT GPUClockSpeed(SWIGTYPE_p_int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUClockSpeed(swigCPtr, SWIGTYPE_p_int.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT GPUVRAMClockSpeed(SWIGTYPE_p_int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUVRAMClockSpeed(swigCPtr, SWIGTYPE_p_int.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT GPUTemperature(SWIGTYPE_p_double data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUTemperature(swigCPtr, SWIGTYPE_p_double.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT GPUHotspotTemperature(SWIGTYPE_p_double data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUHotspotTemperature(swigCPtr, SWIGTYPE_p_double.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT GPUPower(SWIGTYPE_p_double data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUPower(swigCPtr, SWIGTYPE_p_double.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT GPUTotalBoardPower(SWIGTYPE_p_double data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUTotalBoardPower(swigCPtr, SWIGTYPE_p_double.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT GPUFanSpeed(SWIGTYPE_p_int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUFanSpeed(swigCPtr, SWIGTYPE_p_int.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT GPUVRAM(SWIGTYPE_p_int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUVRAM(swigCPtr, SWIGTYPE_p_int.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT GPUVoltage(SWIGTYPE_p_int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUMetrics_GPUVoltage(swigCPtr, SWIGTYPE_p_int.getCPtr(data));
    return ret;
  }

}

}
