//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public class IADLXManualGraphicsTuning1 : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXManualGraphicsTuning1(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXManualGraphicsTuning1_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXManualGraphicsTuning1 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXManualGraphicsTuning1(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXManualGraphicsTuning1_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT GetGPUTuningRanges(ADLX_IntRange frequencyRange, ADLX_IntRange voltageRange) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualGraphicsTuning1_GetGPUTuningRanges(swigCPtr, ADLX_IntRange.getCPtr(frequencyRange), ADLX_IntRange.getCPtr(voltageRange));
    return ret;
  }

  public virtual ADLX_RESULT GetGPUTuningStates(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList ppGFXStates) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualGraphicsTuning1_GetGPUTuningStates(swigCPtr, SWIGTYPE_p_p_adlx__IADLXManualTuningStateList.getCPtr(ppGFXStates));
    return ret;
  }

  public virtual ADLX_RESULT GetEmptyGPUTuningStates(SWIGTYPE_p_p_adlx__IADLXManualTuningStateList ppGFXStates) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualGraphicsTuning1_GetEmptyGPUTuningStates(swigCPtr, SWIGTYPE_p_p_adlx__IADLXManualTuningStateList.getCPtr(ppGFXStates));
    return ret;
  }

  public virtual ADLX_RESULT IsValidGPUTuningStates(IADLXManualTuningStateList pGFXStates, SWIGTYPE_p_int errorIndex) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualGraphicsTuning1_IsValidGPUTuningStates(swigCPtr, IADLXManualTuningStateList.getCPtr(pGFXStates), SWIGTYPE_p_int.getCPtr(errorIndex));
    return ret;
  }

  public virtual ADLX_RESULT SetGPUTuningStates(IADLXManualTuningStateList pGFXStates) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualGraphicsTuning1_SetGPUTuningStates(swigCPtr, IADLXManualTuningStateList.getCPtr(pGFXStates));
    return ret;
  }

}

}
