//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public class IADLXManualVRAMTuning2 : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXManualVRAMTuning2(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXManualVRAMTuning2_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXManualVRAMTuning2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXManualVRAMTuning2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXManualVRAMTuning2_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedMemoryTiming(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualVRAMTuning2_IsSupportedMemoryTiming(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT GetSupportedMemoryTimingDescriptionList(SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList ppDescriptionList) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualVRAMTuning2_GetSupportedMemoryTimingDescriptionList(swigCPtr, SWIGTYPE_p_p_adlx__IADLXMemoryTimingDescriptionList.getCPtr(ppDescriptionList));
    return ret;
  }

  public virtual ADLX_RESULT GetMemoryTimingDescription(SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION description) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualVRAMTuning2_GetMemoryTimingDescription(swigCPtr, SWIGTYPE_p_ADLX_MEMORYTIMING_DESCRIPTION.getCPtr(description));
    return ret;
  }

  public virtual ADLX_RESULT SetMemoryTimingDescription(ADLX_MEMORYTIMING_DESCRIPTION description) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualVRAMTuning2_SetMemoryTimingDescription(swigCPtr, (int)description);
    return ret;
  }

  public virtual ADLX_RESULT GetMaxVRAMFrequencyRange(ADLX_IntRange tuningRange) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualVRAMTuning2_GetMaxVRAMFrequencyRange(swigCPtr, ADLX_IntRange.getCPtr(tuningRange));
    return ret;
  }

  public virtual ADLX_RESULT GetMaxVRAMFrequency(SWIGTYPE_p_int freq) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualVRAMTuning2_GetMaxVRAMFrequency(swigCPtr, SWIGTYPE_p_int.getCPtr(freq));
    return ret;
  }

  public virtual ADLX_RESULT SetMaxVRAMFrequency(int freq) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualVRAMTuning2_SetMaxVRAMFrequency(swigCPtr, freq);
    return ret;
  }

}

}
