//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public class IADLXManualPowerTuning : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXManualPowerTuning(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXManualPowerTuning_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXManualPowerTuning obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXManualPowerTuning(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXManualPowerTuning_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT GetPowerLimitRange(ADLX_IntRange tuningRange) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualPowerTuning_GetPowerLimitRange(swigCPtr, ADLX_IntRange.getCPtr(tuningRange));
    return ret;
  }

  public virtual ADLX_RESULT GetPowerLimit(SWIGTYPE_p_int curVal) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualPowerTuning_GetPowerLimit(swigCPtr, SWIGTYPE_p_int.getCPtr(curVal));
    return ret;
  }

  public virtual ADLX_RESULT SetPowerLimit(int curVal) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualPowerTuning_SetPowerLimit(swigCPtr, curVal);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedTDCLimit(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualPowerTuning_IsSupportedTDCLimit(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT GetTDCLimitRange(ADLX_IntRange tuningRange) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualPowerTuning_GetTDCLimitRange(swigCPtr, ADLX_IntRange.getCPtr(tuningRange));
    return ret;
  }

  public virtual ADLX_RESULT GetTDCLimit(SWIGTYPE_p_int curVal) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualPowerTuning_GetTDCLimit(swigCPtr, SWIGTYPE_p_int.getCPtr(curVal));
    return ret;
  }

  public virtual ADLX_RESULT SetTDCLimit(int curVal) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXManualPowerTuning_SetTDCLimit(swigCPtr, curVal);
    return ret;
  }

}

}
